dialogclassifier/dialogclassifier/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('intent_marker/', include('intent_marker.urls')),
]
urlpatterns += staticfiles_urlpatterns()

"""
Initializes task queue
"""
from intent_marker.custom_helpers import task_queue

dialogclassifier/intent_marker/urls.py
from django.urls import path
from . import views

app_name = 'intent_marker'
urlpatterns = [
    path('', views.index, name='index'),
    path('dialog/save_data', views.save_data, name='save_data'),
    path('dialog/<str:user>', views.dialog, name='dialog'),
    path('stat/', views.total_stat, name='total_stat'),
    path('pie/', views.topic_pie, name='topic_pie'),
    # path('stat/<str:user>', views.user_stat, name='user_stat'),
    # path('stat/date/<str:dte>', views.date_stat, name='date_stat'),
    path('report/', views.marked_results_report_index, name='report_index'),
    path('report/total', views.marked_results_total_report, name='report_total'),
    path('report/detail/<str:chat_dte>', views.marked_results_report_by_date, name='report_by_date'),
    path('report/save/<str:chat_dte>', views.marked_results_save_report, name='save_report'),
]

dialogclassifier/intent_marker/models.py
from django.db import models
from django.contrib.postgres import fields
from datetime import datetime


# Create your models here.

class Topic(models.Model):
    topic_name = models.CharField(max_length=255, unique=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.topic_name


class Subtopic(models.Model):
    class Meta:
        unique_together = (('subtopic_name', 'topic_ref'),)

    subtopic_name = models.CharField(max_length=255, default='UNKNOWN')
    active = models.BooleanField(default=True)
    topic_ref = models.ForeignKey(Topic, on_delete=models.SET_DEFAULT, default=-1)

    def __str__(self):
        return f'{self.subtopic_name} - {self.topic_ref}'


class MarkedResult(models.Model):
    class Meta:
        unique_together = (('chat_date', 'client_id'),)
        indexes = [
            models.Index(fields=['chat_date', ]),
            models.Index(fields=['client_id', ]),

        ]

    chat_date = models.DateField()
    client_id = models.CharField(max_length=6)
    topic = models.ForeignKey(Topic, on_delete=models.SET_DEFAULT, default=-1)
    subtopic = models.ForeignKey(Subtopic, on_delete=models.SET_DEFAULT, default=-1)
    custom_topic = models.CharField(max_length=800, null=True)
    custom_subtopic = models.CharField(max_length=800, null=True)
    aggressive_client = models.BooleanField(default=False)
    non_standard_question = models.BooleanField(default=False)
    chosen_phrases = fields.ArrayField(models.TextField())

    def __str__(self):
        return f'{self.client_id};{self.topic};{self.subtopic};{self.custom_topic};{self.custom_subtopic};{self.aggressive_client};{self.non_standard_question};{self.chosen_phrases}'


class ParsedDialogs(models.Model):
    class Meta:
        unique_together = (('cus_id', 'dialog_time', 'session', 'event_id'),)
        indexes = [
            models.Index(fields=['cus_id', ]),
            models.Index(fields=['dialog_time', ]),
            models.Index(fields=['dialog_date', ]),
            models.Index(fields=['cus_id', 'dialog_time', ]),
            models.Index(fields=['cus_id', 'dialog_date']),
        ]

    cus_id = models.CharField(max_length=6)
    dialog_time = models.DateTimeField()
    dialog_date = models.DateField(null=True)
    session = models.CharField(max_length=16)
    event_id = models.IntegerField()
    genesys_id = models.CharField(max_length=16)
    flag = models.CharField(max_length=6)
    user_id = models.CharField(max_length=7)
    phrase = models.TextField()
    processed = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.cus_id};{self.dialog_time};{self.session};{self.event_id};{self.genesys_id};{self.flag};{self.user_id};{self.phrase}'


class TaskDateRange(models.Model):
    start_date = models.DateField(default=datetime.now().date())
    end_date = models.DateField(default=datetime.now().date())

    def __str__(self):
        return f'{self.start_date}{self.end_date}'


class TaskList(models.Model):
    class Meta:
        db_table = 'intent_marker_task_list'
        managed = False

    dialog_list = fields.JSONField(primary_key=True)


class MarkedResultsReport(models.Model):
    class Meta:
        db_table = 'intent_marker_results_report'
        managed = False

    id = models.IntegerField(primary_key=True)
    chat_date = models.DateField()
    client_id = models.CharField(max_length=6)
    topic_id = models.IntegerField()
    topic_name = models.CharField(max_length=255)
    subtopic_id = models.IntegerField()
    subtopic_name = models.CharField(max_length=255)
    custom_topic = models.CharField(max_length=800)
    custom_subtopic = models.CharField(max_length=800)
    aggressive_client = models.BooleanField()
    non_standard_question = models.BooleanField()
    chosen_phrases = fields.ArrayField(models.TextField())


class LogRecord(models.Model):
    class Meta:
        indexes = [
            models.Index(fields=['record_time', ]),
            models.Index(fields=['user', ]),
        ]

    record_time = models.DateTimeField(auto_now_add=True)
    user = models.CharField(max_length=32)
    user_ip = models.CharField(max_length=15)
    user_host = models.TextField()
    request = models.TextField()


class UserStat(models.Model):
    class Meta:
        indexes = [
            models.Index(fields=['dte', ]),
            models.Index(fields=['user', ]),
        ]

    dte = models.DateField(default=datetime.now().date())
    user = models.CharField(max_length=32)
    records_done = models.IntegerField(null=False)

dialogclassifier/intent_marker/views.py
import json
import csv
from queue import Empty
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.template import RequestContext
from django.utils.encoding import smart_str
from django.views.decorators.csrf import csrf_exempt
from django.core.cache import cache
import logging
from .models import Topic, ParsedDialogs, MarkedResult, Subtopic, UserStat, MarkedResultsReport
from .custom_helpers import generate_seed, task_queue, log_record, save_stat
import requests
from dialogclassifier.settings import ELASTIC_URL

logger = logging.getLogger(__name__)


# Create your views here.
def index(request):
    """
    Start page
    """
    return redirect('dialog/{user}'.format(user=generate_seed()))


def total_stat(request):
    """
    Stat by users (all)
    """
    log_record('UNKNOWN', request)
    data = {'context': [{'date': x.dte, 'user': x.user, 'records': x.records_done} for x in UserStat.objects.all()]}
    return render(request, 'intent_marker/user_stat.html', data, RequestContext(request))


def topic_pie(request):
    """
    Iframe with Kibana pie chart, showing share by topics % subtopics
    """
    log_record('UNKNOWN', request)
    return render(request, 'intent_marker/topic_pie.html', None, RequestContext(request))


def user_stat(request, user):
    """
    Stat of a specific user
    """
    log_record(user, request)
    data = {'context': [{'date': x.dte, 'user': x.user, 'records': x.records_done} for x in
                        UserStat.objects.filter(user=user)]}
    return render(request, 'intent_marker/user_stat.html', data, RequestContext(request))


def date_stat(request, dte):
    """
    Stat filtered by date
    """
    log_record('UNKNOWN', request)
    data = {'context': [{'date': x.dte, 'user': x.user, 'records': x.records_done} for x in
                        UserStat.objects.filter(dte=dte)]}
    return render(request, 'intent_marker/user_stat.html', data, RequestContext(request))


def marked_results_report_index(request):
    """
    Reports base page
    """
    log_record('UNKNOWN', request)
    data = {'context': [x for x in MarkedResultsReport.objects.values('chat_date').distinct()]}
    return render(request, 'intent_marker/report_index.html', data, RequestContext(request))


def marked_results_total_report(request):
    """
    Shows all marked dialogs
    """
    log_record('UNKNOWN', request)
    data = {'context': [{
        'id': x.id,
        'chat_date': x.chat_date,
        'client_id': x.client_id,
        'topic_id': x.topic_id,
        'topic_name': x.topic_name,
        'subtopic_id': x.subtopic_id,
        'subtopic_name': x.subtopic_name,
        'custom_topic': x.custom_topic,
        'custom_subtopic': x.custom_subtopic,
        'aggressive_client': x.aggressive_client,
        'non_standard_question': x.non_standard_question,
        'chosen_phrases': x.chosen_phrases
    } for x in MarkedResultsReport.objects.all()]}
    return render(request, 'intent_marker/report_detail.html', data, RequestContext(request))


def marked_results_report_by_date(request, chat_dte):
    """
    Shows marked dialogs by date
    """
    log_record('UNKNOWN', request)
    data = {
        'chat_dte': chat_dte,
        'context': [{
            'id': x.id,
            'chat_date': x.chat_date,
            'client_id': x.client_id,
            'topic_id': x.topic_id,
            'topic_name': x.topic_name,
            'subtopic_id': x.subtopic_id,
            'subtopic_name': x.subtopic_name,
            'custom_topic': x.custom_topic,
            'custom_subtopic': x.custom_subtopic,
            'aggressive_client': x.aggressive_client,
            'non_standard_question': x.non_standard_question,
            'chosen_phrases': x.chosen_phrases
        } for x in MarkedResultsReport.objects.filter(chat_date=chat_dte)]}
    return render(request, 'intent_marker/report_detail.html', data, RequestContext(request))


def marked_results_save_report(request, chat_dte):
    """
    Hook to save report
    """
    log_record('UNKNOWN', request)
    response = HttpResponse(content_type='application/force-download')
    response['Content-Disposition'] = f'attachment; filename=report_{smart_str(chat_dte)}.csv'

    writer = csv.writer(response, csv.excel)
    response.write(u'\ufeff'.encode('utf-8'))
    writer.writerow([
        smart_str(u'id'),
        smart_str(u'chat_date'),
        smart_str(u'client_id'),
        smart_str(u'topic_id'),
        smart_str(u'topic_name'),
        smart_str(u'subtopic_id'),
        smart_str(u'subtopic_name'),
        smart_str(u'custom_topic'),
        smart_str(u'custom_subtopic'),
        smart_str(u'aggressive_client'),
        smart_str(u'non_standard_question'),
        smart_str(u'chosen_phrases'),
    ])
    for x in MarkedResultsReport.objects.filter(chat_date=chat_dte):
        writer.writerow([
            smart_str(x.id),
            smart_str(x.chat_date),
            smart_str(x.client_id),
            smart_str(x.topic_id),
            smart_str(x.topic_name),
            smart_str(x.subtopic_id),
            smart_str(x.subtopic_name),
            smart_str(x.custom_topic),
            smart_str(x.custom_subtopic),
            smart_str(x.aggressive_client),
            smart_str(x.non_standard_question),
            smart_str(x.chosen_phrases)
        ])
    return response


@csrf_exempt
def dialog(request, user):
    """
    Display new workpage for user (with new dialog to check)
    """
    log_record(user, request)
    topics = {x.topic_name: sorted([y.subtopic_name for y in x.subtopic_set.filter(active=True).all()]) for x in
              Topic.objects.filter(active=True)}
    # use cache to ensure that user receives the same record until he processes it or inactive for time X
    cached_record = cache.get(user)
    if cached_record:
        task = cached_record
    else:
        try:
            task = task_queue.get(block=False).dialog_list
        except Empty:
            return HttpResponse("<h1>Задачи закончились</h1>")
    next_record = {
        'context': {
            'customer': task['cus_id'],
            'dialog_date': task['dialog_date'],
            'dialog': sorted(task['dialog'],key=lambda d: (d['dialog_time'],d['event_id']))
        },
        'topics': sorted(topics.keys()),
        'topic_meta': topics,
    }
    cache.set(user, task)
    # set TTL for cached task
    cache.touch(user, 60 * 60 * 2)
    return render(request, 'intent_marker/dialog.html', next_record, RequestContext(request))


@csrf_exempt
def save_data(request):
    """
    Hook to save marked dialog
    """
    if request.method != 'POST':
        return HttpResponseBadRequest('<h1>Method not allowed</h1>')
    data = json.loads(request.body)
    user = data['user'].split('/')[-1]

    log_record(user, request)

    cached_record = cache.get(user)

    try:
        top = Topic.objects.get(topic_name=data['topic'], active=True) if data['topic'] != '' else Topic.objects.get(
            topic_name='')
        sbtp = Subtopic.objects.get(subtopic_name=data['subtopic'], topic_ref=top, active=True) if data[
                                                                                                       'topic'] != '' else top.subtopic_set.get(
            subtopic_name='')

        obj, created = MarkedResult.objects.update_or_create(
            chat_date=cached_record['dialog_date'],
            client_id=data['client_id'],
            topic=top,
            subtopic=sbtp,
            custom_topic=data['custom_topic'],
            custom_subtopic=data['custom_subtopic'],
            aggressive_client=data['agressive_client'],
            non_standard_question=data['non_standart_question'],
            chosen_phrases=[x['phrase'] for x in data['chosen_phrases']],
        )

        payload = json.dumps({
            'id': obj.id,
            'chat_date': str(obj.chat_date),
            'client_id': obj.client_id,
            'topic_id': obj.topic.id,
            'topic_name': obj.topic.topic_name,
            'subtopic_id': obj.subtopic.id,
            'subtopic_name': obj.subtopic.subtopic_name,
            'custom_topic': obj.custom_topic,
            'custom_subtopic': obj.custom_subtopic,
            'aggressive_client': obj.aggressive_client,
            'non_standard_question': obj.non_standard_question,
            'chosen_phrases': obj.chosen_phrases
        })

        requests.post(ELASTIC_URL + f'{obj.id}?pretty', payload)

        for parsed_rec in ParsedDialogs.objects.filter(dialog_date=cached_record['dialog_date'],
                                                       cus_id=cached_record['cus_id']):
            parsed_rec.processed = True
            parsed_rec.save()
            # Remove record from cache after it's processed
            cache.delete(user)

    except Exception as e:
        print(e)
    save_stat(user)
    return HttpResponse('')

dialogclassifier/intent_marker/templates/intent_marker/dialog.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'intent_marker/head.html' %}
    <script>
        function saveData(e) {
            var top = document.getElementById('topic-selector');
            var topicRes = top.options[top.selectedIndex].value;

            var subtop = document.getElementById('subtopic-selector');
            var subtopicRes = subtop.options[subtop.selectedIndex].value;

            var customTop = document.getElementById('topic-custom').value;
            var customSubtop = document.getElementById('subtopic-custom').value;

            var data = {
                chosen_phrases: getData(),
                client_id: $('#client_id').text(),
                topic: topicRes,
                subtopic: subtopicRes,
                custom_topic: customTop,
                custom_subtopic: customSubtop,
                non_standart_question: document.getElementById('nonStandartQuestion').checked,
                agressive_client: document.getElementById('agressiveClient').checked,
                user: window.location.pathname.slice(1)
            };

            if (
                (topicRes && subtopicRes && !customTop && !customSubtop) ||
                (topicRes && !subtopicRes && !customTop && customSubtop) ||
                (!topicRes && !subtopicRes && customTop && customSubtop)
            ) {
                $.ajax({
                    type: "POST",
                    url: "save_data",
                    data: JSON.stringify(data),
                    dataType: "json",
                    contentType: "application/json; charset=UTF-8",
                    complete: function () {
                        location.reload();
                    }
                });
            } else {
                alert('Требуется заполнить одно из полей "Тема" и одно из полей "Другая тема"');
                location.reload()
            }
        }

        function getData() {
            {#var table = document.querySelectorAll('form[name=markers] table tbody tr');#}
            var $table = $('form[name=markers] table tbody tr');
            var data = [];
            $table
                .each(function (i, row) {
                    var flag = $(this).find("input[type=checkbox]:checked").length;

                    if (flag) {
                        data.push(
                            {
                                phrase: $(this).find(":nth-child(2)").text(),
                                checked: true
                            });
                    }
                });
            return data;
        }
    </script>
    <script>
        $(document).ready(function () {
            $("#shittyBtn").on('click', saveData);
        });
    </script>
</head>
<body>
<div class="container-fluid">
    <h3>{{ context.dialog_date }}</h3>
    <h3 id="client_id">{{ context.customer }}</h3>
    <form name="markers" id="inpForm">
        {% csrf_token %}
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>Участник</th>
                <th>Текст сообщения</th>
                <th>Сохранить фразу</th>
            </tr>
            </thead>
            {% for phrase in context.dialog %}
                <tr class="{% if phrase.flag == 'CLIENT' %} 'success' {% else %} 'default'{% endif %}">
                    <td style="font-weight: bold">
                        {{ phrase.flag }}
                    </td>
                    <td>{{ phrase.phrase }}</td>
                    <td>
                        <form>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">
                                        <input type="checkbox" {% if phrase.flag != 'CLIENT' %}
                                            {{ 'disabled' }} {{ 'hidden' }} {% else %} {{ '' }} {% endif %}  />
                                    </div>
                                </div>
                            </div>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <div class="container-fluid form-group">
            <div class="row">
                <div class="col-md-6">
                    <h5 style="font-weight: bold">Тема</h5>
                    <select class="form-control" id="topic-selector">
                        <option value="" selected="selected"></option>
                        {% for top in topics %}
                            <option value="{{ top }}">{{ top }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-6">
                    <h5 style="font-weight: bold">Подтема</h5>
                    <select class="form-control" id="subtopic-selector">
                        <option selected="selected"></option>
                    </select>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-6">
                    <h5 style="font-weight: bold">Другая тема</h5>
                    <input type="text" class="form-control" id="topic-custom"
                           placeholder="Введите тему, если она не указана в списке выше">
                </div>
                <div class="col-md-6">
                    <h5 style="font-weight: bold">Другая подтема</h5>
                    <input type="text" class="form-control" id="subtopic-custom"
                           placeholder="Введите тему, если она не указана в списке выше">
                </div>
            </div>
            <br>
            <div class="row container-fluid">
                <div class="col-md-6">
                    <h5 style="font-weight: bold">Признак нестандартной темы</h5>
                    <div class="form-group form-check">
                        <input type="checkbox" class="form-check-input" id="nonStandartQuestion">
                        <label class="form-check-label" for="exampleCheck1">Отметьте пункт, если формулировка
                            нестанартна для этой темы</label>
                    </div>
                </div>
                <div class="col-md-6">
                    <h5 style="font-weight: bold">Агрессивный клиент</h5>
                    <div class="form-group form-check">
                        <input type="checkbox" class="form-check-input" id="agressiveClient">
                        <label class="form-check-label" for="exampleCheck1">Отметьте пункт, если клиент
                            агрессивен</label>
                    </div>
                </div>
            </div>

            <div class="row">
                <input id="shittyBtn" type="button" value="Сохранить" class="btn btn-primary col-lg"/>
            </div>
        </div>
    </form>
    <br>
    <br>
</div>
<script>
    jQuery(function ($) {

        var topiclist = {{ topic_meta | safe }};

        var $subtopics = $('#subtopic-selector');
        $('#topic-selector').change(function () {
            var topic = $(this).val(), pairs = topiclist[topic] || [];
            pairs.sort();
            var html = $.map(pairs, function (lcn) {
                return '<option value="' + lcn + '">' + lcn + '</option>'
            }).join('');
            $subtopics.html(html);
        });
    });
</script>
</body>
</html>

dialogclassifier/intent_marker/templates/intent_marker/head.html
<meta charset="UTF-8">
<title>Intent maker 2.0.0</title>
{% load static %}
<link rel="stylesheet" href="{% static "bootstrap.min.css" %}"/>
<link rel="stylesheet" href="{% static "style.css" %}"/>
<script src="{% static "popper.min.js" %}"></script>
<script src="{% static "jquery-1.12.4.js" %}"></script>
<script src="{% static "bootstrap.min.js" %}"></script>
<script src="{% static "json3.min.js" %}"></script>
<script src="{% static "main.js" %}"></script>

dialogclassifier/intent_marker/templates/intent_marker/report_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'intent_marker/head.html' %}
</head>
<body>
<div class="container-fluid">

    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <a href="{% url 'intent_marker:total_stat' %}" class="btn btn-primary">USER STAT</a>
                </div>
                <div class="col-md-4">
                    <a href="{% url 'intent_marker:topic_pie' %}" class="btn btn-primary">TOPIC PIE</a>
                </div>
                <div class="col-md-4">
                    <a href="{% url 'intent_marker:report_index' %}" class="btn btn-primary">REPORT</a>
                </div>
            </div>
        </div>
    </div>
    {% if chat_dte %}
        <h4><a href="{% url 'intent_marker:save_report' chat_dte %}" class="btn btn-danger">DOWNLOAD REPORT</a></h4>
    {% endif %}
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th>chat_date</th>
            <th>client_id</th>
            <th>topic_id</th>
            <th>topic_name</th>
            <th>subtopic_id</th>
            <th>subtopic_name</th>
            <th>custom_topic</th>
            <th>custom_subtopic</th>
            <th>aggressive_client</th>
            <th>non_standard_question</th>
            <th>chosen_phrases</th>
        </tr>
        </thead>
        <tbody>
        {% for rec in context %}
            <tr>
                <td>{{ rec.chat_date }}</td>
                <td>{{ rec.client_id }}</td>
                <td>{{ rec.topic_id }}</td>
                <td>{{ rec.topic_name }}</td>
                <td>{{ rec.subtopic_id }}</td>
                <td>{{ rec.subtopic_name }}</td>
                <td>{{ rec.custom_topic }}</td>
                <td>{{ rec.custom_subtopic }}</td>
                <td>{{ rec.aggressive_client }}</td>
                <td>{{ rec.non_standard_question }}</td>
                <td>{{ rec.chosen_phrases }}</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
</div>
</body>
</html>

dialogclassifier/intent_marker/templates/intent_marker/report_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'intent_marker/head.html' %}
</head>
<body>
<div class="container-fluid">

    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <a href="{% url 'intent_marker:total_stat' %}" class="btn btn-primary">USER STAT</a>
                </div>
                <div class="col-md-6">
                    <a href="{% url 'intent_marker:topic_pie' %}" class="btn btn-primary">TOPIC PIE</a>
                </div>
            </div>
        </div>
    </div>
    <h2>DIALOG DATES:</h2>
    <ul>
        <li><h3>TOTAL: <a href="{% url 'intent_marker:report_total' %}" class="btn btn-info">VIEW</a></h3></li>
        {% for rec in context %}
            <li><h3>{{ rec.chat_date.isoformat }}: <a class="btn btn-primary"
                                                      href="{% url 'intent_marker:report_by_date' rec.chat_date %}">VIEW</a>
                <a class="btn btn-danger" href="{% url 'intent_marker:save_report' rec.chat_date %}">DOWNLOAD</a>

            </h3></li>
        {% endfor %}
    </ul>

    </tbody>
    </table>
</div>
</body>
</html>

dialogclassifier/intent_marker/templates/intent_marker/topic_pie.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'intent_marker/head.html' %}
</head>
<body>
<div class="container-fluid">
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <a href="{% url 'intent_marker:total_stat' %}" class="btn btn-primary">USER STAT</a>
                </div>
                <div class="col-md-6">
                    <a href="{% url 'intent_marker:report_index' %}" class="btn btn-primary">REPORT</a>
                </div>
            </div>
        </div>
    </div>
    <iframe src="http://inhuman_test:5601/app/kibana#/visualize/edit/AWYQ-74EQZUxg83KzUk8?embed=true&_g=(refreshInterval%3A('%24%24hashKey'%3A'object%3A964'%2Cdisplay%3AOff%2Cpause%3A!f%2Csection%3A0%2Cvalue%3A0)%2Ctime%3A(from%3Anow-1y%2Cmode%3Aquick%2Cto%3Anow))"
            height="960" width="100%"></iframe>
</div>
</body>
</html>

dialogclassifier/intent_marker/templates/intent_marker/user_stat.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'intent_marker/head.html' %}
</head>
<body>
<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <a href="{% url 'intent_marker:topic_pie' %}" class="btn btn-primary">TOPIC PIE</a>
            </div>
            <div class="col-md-6">
                <a href="{% url 'intent_marker:report_index' %}" class="btn btn-primary">REPORT</a>
            </div>
        </div>
    </div>
</div>
<iframe src="http://inhuman_test:5601/app/kibana#/visualize/edit/AWYfdah3QZUxg83KzqZY?embed=true&_g=(refreshInterval%3A(display%3AOff%2Cpause%3A!f%2Cvalue%3A0)%2Ctime%3A(from%3Anow-1y%2Cmode%3Aquick%2Cto%3Anow))"
        height="960" width="100%"></iframe>
{#    <table class="table table-striped table-bordered table-hover">#}
{#        <thead>#}
{#        <tr>#}
{#            <th>WORK DATE</th>#}
{#            <th>USER</th>#}
{#            <th>RECORDS DONE</th>#}
{#        </tr>#}
{#        </thead>#}
{#        <tbody>#}
{#        {% for rec in context %}#}
{#            <tr>#}
{#                <td><a href="{% url 'intent_marker:date_stat' rec.date %}">{{ rec.date.isoformat }}</a></td>#}
{#                <td><a href="{% url 'intent_marker:user_stat' rec.user %}">{{ rec.user }}</a></td>#}
{#                <td>{{ rec.records }}</td>#}
{#            </tr>#}
{#        {% endfor %}#}
{##}
{#        </tbody>#}
{#    </table>#}
</div>
</body>
</html>